### ISSUE TITLE
pre-flight checks failing when using module

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#112] opened 2018-06-06 17:13 UTC
## What you expected to happen?

Use of Kubernetes 2.0.2 module installs without errors

## What happened?

I'm getting some errors, one that's critical and prevents things from working:

```
# puppet apply --hiera_config=hiera.yaml --modulepath modules:site manifests/nodes.pp
Warning: ModuleLoader: module 'kubernetes' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
Notice: Compiled catalog for foobar.llnl.gov in environment production in 0.81 seconds
Notice: /Stage[main]/Profiles::Container_orchestration::Kubernetes_master/Exec[swapoff]/returns: executed successfully
Notice: /Stage[main]/Kubernetes::Repos/Yumrepo[docker]/ensure: created
Notice: /Stage[main]/Kubernetes::Repos/Yumrepo[kubernetes]/ensure: created
Notice: /Stage[main]/Kubernetes::Packages/Exec[set up bridge-nf-call-iptables]/returns: executed successfully
Notice: /Stage[main]/Kubernetes::Packages/Package[docker-engine]/ensure: created
Notice: /Stage[main]/Kubernetes::Packages/File_line[set systemd cgroup docker]/ensure: created
Notice: /Stage[main]/Kubernetes::Packages/Archive[etcd-v3.1.12-linux-amd64.tar.gz]/ensure: download archive from https://github.com/coreos/etcd/releases/download/v3.1.12/etcd-v3.1.12-linux-amd64.tar.gz to /etcd-v3.1.12-linux-amd64.tar.gz and extracted in /usr/local/bin with cleanup
Notice: /Stage[main]/Kubernetes::Packages/Package[kubelet]/ensure: created
Notice: /Stage[main]/Kubernetes::Packages/Package[kubectl]/ensure: created
Notice: /Stage[main]/Kubernetes::Packages/Package[kubeadm]/ensure: created
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki]/ensure: created
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd]/ensure: created
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/ca.crt]/ensure: defined content as '{md5}3b5f2b95da2e673f0cd8320e8d2d6bc0'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/ca.key]/ensure: defined content as '{md5}fbf9a5cefc0a618db703858d2b1fe23e'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/client.crt]/ensure: defined content as '{md5}decbe90d92876366143a24d97521dcf7'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/client.key]/ensure: defined content as '{md5}874345a1c97f1c6dd5a52571773a2a71'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/peer.crt]/ensure: defined content as '{md5}42761016e75a81fb37283f88adebfb31'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/peer.key]/ensure: defined content as '{md5}44cda0692a965e16b7e1b548e261d70a'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/server.crt]/ensure: defined content as '{md5}5c86245114732e0bacf4188e8f598ac7'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/etcd/server.key]/ensure: defined content as '{md5}2c41ad0d91b4dba6b423a72b3211859c'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/ca.crt]/ensure: defined content as '{md5}335356d0b00534d634f1eae328e4c72c'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/ca.key]/ensure: defined content as '{md5}ef7cdce1cdc4a223fff42b92de052f99'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/sa.pub]/ensure: defined content as '{md5}059fc1ddf74b92de8fa6a674a41542ed'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/pki/sa.key]/ensure: defined content as '{md5}43d9712a1109da1f65b6eb71c419398a'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/systemd/system/etcd.service]/ensure: defined content as '{md5}d94bdb20fb9238e7f76b8e3ecdc6bfa9'
Notice: /Stage[main]/Kubernetes::Config/File[/etc/kubernetes/config.yaml]/ensure: defined content as '{md5}29d9105d8fbaf5731a6929b7a2f3a3b4'
Notice: /Stage[main]/Kubernetes::Service/Service[docker]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Kubernetes::Service/Service[etcd]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: [init] Using Kubernetes version: v1.10.4
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: [init] Using Authorization modes: [Node RBAC]
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: [preflight] Running pre-flight checks.
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns:     [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns:     [WARNING FileExisting-crictl]: crictl not found in system path
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: [preflight] Some fatal errors occurred:
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns:     [ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
Error: 'kubeadm init --config '/etc/kubernetes/config.yaml'' returned 2 instead of one of [0]
Error: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[foobar]/Exec[kubeadm init]/returns: change from 'notrun' to ['0'] failed: 'kubeadm init --config '/etc/kubernetes/config.yaml'' returned 2 instead of one of [0]
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Dependency Exec[kubeadm init] has failures: true
Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Skipping because of failed dependencies
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install Kubernetes dashboard]: Dependency Exec[kubeadm init] has failures: true
Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[Install Kubernetes dashboard]: Skipping because of failed dependencies
Notice: Applied catalog in 88.03 seconds
```

## How to reproduce it?

See the command I ran above.

## Versions:

```
$ puppet --version
5.3.5

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

$ docker version OR crictl version
Docker version 17.03.1-ce, build c6d412e

$ facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

$ puppet module list
/etc/puppetlabs/code/environments/production/modules (no modules installed)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)
```

## Other Logs

The file /etc/kubernetes/config.yaml is probably relevant. I replaced my hostname with foobar, and my IP address with 4.3.2.1:

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 4.3.2.1
etcd:
  endpoints:
  - https://4.3.2.1:2379
  caFile: /etc/kubernetes/pki/etcd/ca.crt
  certFile: /etc/kubernetes/pki/etcd/client.crt
  keyFile: /etc/kubernetes/pki/etcd/client.key
CertificatesDir: /etc/kubernetes/pki
nodeName: foobar
networking:
  podSubnet: 10.32.0.0/12
  serviceSubnet: 10.96.0.0/12
apiServerExtraArgs:
  endpoint-reconciler-type: lease

token: 74cdce.4a06bc09e319b53b
apiServerCertSANs:
```

**Comment by scotty-c** [comment] 2018-06-07 08:55
@vrmerlin it looks like etcd has not started. Can you confirm that in the logs?

**Comment by vrmerlin** [comment] 2018-06-07 19:20
It looks like etcd is indeed running:

```
# systemctl status etcd
● etcd.service - etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-06-06 10:01:11 PDT; 1 day 2h ago
     Docs: https://github.com/coreos/etcd
 Main PID: 13154 (etcd)
    Tasks: 7
   Memory: 3.6M
   CGroup: /system.slice/etcd.service
           └─13154 /usr/local/bin/etcd .......

Jun 06 10:01:11 foobar.llnl.gov etcd[13154]: set the initial cluster version to 3.1
Jun 06 10:01:11 foobar.llnl.gov etcd[13154]: enabled capabilities for version 3.1
Jun 06 10:01:11 foobar.llnl.gov etcd[13154]: published {Name:foobar ClientURLs:[https://128.115.51.1:2379]} to cluster b247e148a129351d
Jun 06 10:01:11 foobar.llnl.gov etcd[13154]: ready to serve client requests
Jun 06 10:01:11 foobar.llnl.gov systemd[1]: Started etcd.
Jun 06 10:01:11 foobar.llnl.gov etcd[13154]: serving client requests on 128.115.51.1:2379
Jun 06 10:01:11 foobar.llnl.gov systemd[1]: Dependency Conflicts=etcd.service dropped from unit etcd.service
Jun 06 10:01:11 foobar.llnl.gov systemd[1]: Dependency Conflicts=etcd.service dropped from unit etcd.service
Jun 06 10:32:41 foobar.llnl.gov systemd[1]: Dependency Conflicts=etcd.service dropped from unit etcd.service
Jun 06 10:42:01 foobar.llnl.gov systemd[1]: Dependency Conflicts=etcd.service dropped from unit etcd.service
```
How do i check if the certs are correct and if the services are able to hit it?

**Comment by rustymunkey** [comment] 2018-06-11 09:59
I am having the exact same problem. I followed the readme.md to install kubernetes on a clean vm and ran into the same pre-flight error.

```
# puppet agent -t
[...]
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[test-vm]/Exec[kubeadm init]/returns: [preflight] Some fatal errors occurred:
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[test-vm]/Exec[kubeadm init]/returns:    [ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[test-vom]/Exec[kubeadm init]/returns: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
[...]
Notice: Applied catalog in 29.68 seconds
```

etcd is running:

```# systemctl status etcd
● etcd.service - etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: enabled)
[...]
```

Is there any configuration option, that i am missing? I am quite new to the whole kubernetes world, so it could easily be a user error.

**Comment by scotty-c** [comment] 2018-06-14 06:04
@rustymunkey & @vrmerlin can you copy your hiera files into the issue?

**Comment by davejrt** [comment] 2018-06-19 20:28
@rustymunkey & @vrmerlin in addition to your hiera config, can you run the following with your etcdip and paste the result

`root@kube-master:/etc/kubernetes/pki/etcd# etcdctl --cert-file=server.crt --key-file=server.key --ca-file=ca.crt --endpoints https://<etcd_ip>:2379 cluster-health`

**Comment by rustymunkey** [comment] 2018-06-20 08:09
Yeah, sure!

@davejrt There really seems to be a problem with the certificates:

```root@buildslave-test:/etc/kubernetes/pki/etcd# etcdctl --cert-file=server.crt --key-file=server.key --ca-file=ca.crt --endpoints https://10.1.66.29:2379 cluster-health
2018-06-20 10:06:37.440614 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2018-06-20 10:06:37.441936 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured; error #0: x509: cannot validate certificate for 10.1.66.29 because it doesn't contain any IP SANs

error #0: x509: cannot validate certificate for 10.1.66.29 because it doesn't contain any IP SANs
```

how do i fix it? I used the **puppet/kubetool** docker images for generating the certificates.

and as requested the hiera.yaml

```
kubernetes::bootstrap_controller: true
kubernetes::controller: true
kubernetes::kubernetes_version: 1.10.3-00
kubernetes::kubernetes_package_version: 1.10.3-00
kubernetes::container_runtime: docker
kubernetes::cni_network_provider: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubernetes::cni_pod_cidr: "10.244.0.0/16"
kubernetes::cluster_service_cidr: "10.96.0.0/16"
kubernetes::kubernetes_fqdn: kubernetes.example.com
kubernetes::bootstrap_controller_ip: "%{::ipaddress_ens3}"
kubernetes::etcd_version: '3.1.12'
kubernetes::etcd_initial_cluster: "test-vm=https://%{::ipaddress_ens3}:2380"
kubernetes::etcd_ip: "%{::ipaddress_ens3}"
kubernetes::etcd_peers:
  - 10.1.66.29
kubernetes::kube_dns_ip: "10.96.0.10"
kubernetes::kube_api_service_ip: "10.96.0.1"
kubernetes::kube_api_advertise_address: "%{::ipaddress_ens3}"
kubernetes::api_server_count: 1
kubernetes::controller_address: "10.1.66.29:6443"
kubernetes::install_dashboard: false
kubernetes::taint_master: false
kubernetes::token: 8dce35.ee31967c3c239cba```
followed by a list of certificates and keys.

**Comment by davejrt** [comment] 2018-06-20 13:31
what version of the kubetool are you using? Some of those params are no longer valid in the version of the module. You should be using 2.0.2

**Comment by AranVinkItility** [comment] 2018-06-29 12:57
Running into a similar issue with module version 2.0.2 and kubetool 2.0.2.
Etcd is running on all my nodes and the connection snippet works for me.
In my case the kubelet service is not started (same error as @vrmerlin). If I try to start it manually it says it's unable to start:
```
Jun 29 14:50:54 ics106067213 kubelet[6609]: F0629 14:50:54.763798    6609 server.go:233] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such..
```
This configuration file is missing, however I can't find a mention anywhere in this module. It *might* be the same reason why @vrmerlin is not able to start his cluster.

Possibly related: I also notice the kubelet service is no longer managed by this module since v2.x, is there a reason for this?
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/1.1.0/manifests/service.pp#L41

**Comment by davejrt** [comment] 2018-06-29 20:56
Can you please provide the log of the puppet run where it bootstraps in the
master node?

**Comment by vrmerlin** [comment] 2018-07-06 21:51
Sorry, i'm getting back to this problem after being away on vacation.

@AranVinkItility  That's correct, the file /etc/kubernetes/bootstrap-kubelet.conf is missing for me. You said "Removing kubeadm and reinstalling it solved my similar issue." What do you mean by that? I want to bring up the kubernetes master from a fresh VM without problems or special steps.

@davejrt How do i find that log file?

**Comment by vrmerlin** [comment] 2018-07-06 21:54
I did notice this in my `/var/log/messages`:

```
Jul  6 14:34:32 fisher23-linux yum[12774]: Installed: kubelet-1.10.2-0.x86_64
Jul  6 14:34:35 fisher23-linux chronyd[956]: Selected source 134.9.161.140Jul  6 14:34:35 fisher23-linux yum[12774]: Installed: kubernetes-cni-0.6.0-0.x86_64
Jul  6 14:34:36 fisher23-linux puppet-agent[12795]: (Facter) error while resolving custom fact "docker": 751: unexpected token at ''
Jul  6 14:34:36 fisher23-linux puppet-agent[12795]: (Facter) error while resolving custom fact "docker_server_version": undefined method `[]' for nil:NilClass
Jul  6 14:34:36 fisher23-linux systemd: Configuration file /etc/systemd/system/kubelet.service is marked executable. Please remove executable permission bits. Proceeding anyway.Jul  6 14:34:39 fisher23-linux puppet-agent[12795]: Applied catalog in 0.95 seconds
Jul  6 14:34:44 fisher23-linux yum[12921]: Installed: kubectl-1.10.2-0.x86_64
Jul  6 14:34:56 fisher23-linux yum[12952]: Installed: kubeadm-1.10.2-0.x86_64
```
Is that helpful at all?

**Comment by AranVinkItility** [comment] 2018-07-09 08:06
@vrmerlin I removed kubeadm using my OS package manager (yum, RHEL 7 in my case). After that I did a new puppet run and that solved the issue. Could also be that it needed two runs to succeed though, and it was more of a placebo.

**Comment by davejrt** [comment] 2018-07-09 21:52
@vrmerlin based on the first log you posted and what @scotty-c said your etcd cluster is not starting. Have you verified you're using the correct version of the kubetool for this version of the module.

**Comment by vrmerlin** [comment] 2018-07-17 20:00
@davejrt  as I said in my June 7th posting, it appears that etcd was running successfully. I wasn't trying to run a full cluster version.   I'm not sure what you mean by the correct version of kubetool... doesn't this kubernetes module do the installation of that for me?

**Comment by vrmerlin** [comment] 2018-07-18 20:40
I completely reset my VM to an earlier state, so everything was clean, re-generated the YAML using the kubetool (2.0.2), and ran the puppet script again. It all seems to install fine, until the very end, where again I get this error:

```
[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
```

This is my kubetool command (with my hostname set to foobar, and my IP address set to 1.2.3.4):

```
docker run --rm \
       -v $(pwd):/mnt \
       -e OS=redhat \
       -e VERSION=1.10.2 \
       -e CONTAINER_RUNTIME=docker \
       -e CNI_PROVIDER=weave \
       -e ETCD_INITIAL_CLUSTER=foobar:1.2.3.4 \
       -e ETCD_IP="1.2.3.4" \
       -e KUBE_API_ADVERTISE_ADDRESS="1.2.3.4" \
       -e INSTALL_DASHBOARD=true puppet/kubetool:2.0.2
```

Does that look correct?




Argh,

**Comment by davejrt** [comment] 2018-07-18 23:07
In my experience those errors are caused by problems with the certificates. Have you considered using KREAM to test the module. You can change whatever you want in the config for that to test out your certificates. Using the environment to develop the module this has generally been the cause of our issues. I'm assuming of course here you're setting up a single node cluster?

**Comment by vrmerlin** [comment] 2018-07-18 23:20
This first pass is a single node cluster. Once I figure things out, I'd like to have a master node, and two work nodes.  I'm sorry, I have no idea what KREAM is...?  Did you have a specific test in mind that I should do?

**Comment by vrmerlin** [comment] 2018-07-19 15:04
I originally used the ::ipaddress_eth1 fact, but was getting the error:

```
Warning: Undefined variable '::ipaddress_eth1'; \n   (file & line not available)
```

i.e. that fact is not one that is available for me. Is that part of the problem?

**Comment by davejrt** [comment] 2018-07-20 01:57
Yes, you'll need to use whatever fact corresponds to the interface you want to use.

**Comment by 2ZZ** [comment] 2018-07-21 21:10
Also having this problem. I removed `--client-cert-auth` and `--peer-client-cert-auth` from `templates/etcd/etcd.service.erb` to get it running, looks like something is not right with the cert generation

**Comment by vrmerlin** [comment] 2018-08-08 19:50
@scotty-c  I provided my specific kubetool command, above. Did it look correct? Here it is again (host/IP addresses replaced):

```
docker run --rm \
       -v $(pwd):/mnt \
       -e OS=redhat \
       -e VERSION=1.10.2 \
       -e CONTAINER_RUNTIME=docker \
       -e CNI_PROVIDER=weave \
       -e ETCD_INITIAL_CLUSTER=foobar:1.2.3.4 \
       -e ETCD_IP="1.2.3.4" \
       -e KUBE_API_ADVERTISE_ADDRESS="1.2.3.4" \
       -e INSTALL_DASHBOARD=true puppet/kubetool:2.0.2
```

**Comment by scotty-c** [comment] 2018-08-08 21:39
@vrmerlin it looks ok, the most important information has been redacted. What are the etcd logs saying? if there is an x509 issue you will see it there.

**Comment by khaefeli** [comment] 2018-08-13 18:58
@vrmerlin some ideas:

- make sure `/etc/hosts` / dns is resolving your foobar / hostname configured in etcd
- `hostname -f` should match your ETCD_INITIAL_CLUSTER 
- check if kubectl init maybe proxy to an `http_proxy` and tries to access localhost an this proxy (instead of accessing etcd's localhost)
- reset the whole Kubernetes config `kubeadm reset`, regenerate the certs & insert them into hiera again, run puppet again
- paste the systemd unit file `/etc/systemd/system/etcd.service`

side note: I think your facter variables above are wrong.
Maybe my .env config helps (cluster for 3)

```
OS=debian
VERSION=1.11.0
CONTAINER_RUNTIME=containerd
CNI_PROVIDER=weave
ETCD_INITIAL_CLUSTER=kube-controller1.domain.com:10.12.37.160,kube-controller2.domain.com:10.12.38.170,kube-controller3.domain.com:10.12.44.170
ETCD_IP="%{::ipaddress_br0}" 
KUBE_API_ADVERTISE_ADDRESS="%{::ipaddress_br0}" 
INSTALL_DASHBOARD=true
```

**Comment by ndelic0** [comment] 2018-08-20 19:10
Reporting the same issue.

`puppet --version 5.5.2`

Puppet module version `2.0.2`

Docker:
`docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64`

`Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64
 Experimental: false`

Kubectl version
`kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

OS:
`facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}`

etcd cluster members:
`[root@control-01 ~]# ETCDCTL_API=3 etcdctl member list \
 --endpoints=https://10.0.0.11:2379 \
 --cacert=/etc/kubernetes/pki/etcd/ca.crt  \
 --cert=/etc/kubernetes/pki/etcd/client.crt \
 --key=/etc/kubernetes/pki/etcd/client.key
2018-08-20 20:59:46.912823 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
f252c52dd348c25, started, control-03, https://10.0.0.13:2380, https://10.0.0.13:2379
89681c104bf9f0d6, started, control-02, https://10.0.0.12:2380, https://10.0.0.12:2379
dea6586d25883262, started, control-01, https://10.0.0.11:2380, https://10.0.0.11:2379`

The error:

> Info:`

 Applying configuration version 'puppetserver-01-production-7332ab5b9ea'
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: [init] Using Kubernetes version: v1.10.7
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: [init] Using Authorization modes: [Node RBAC]
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: [preflight] Running pre-flight checks.
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [WARNING FileExisting-crictl]: crictl not found in system path
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: [preflight] Some fatal errors occurred:
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR Port-6443]: Port 6443 is in use
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR Port-10250]: Port 10250 is in use
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR Port-10251]: Port 10251 is in use
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR Port-10252]: Port 10252 is in use
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns:  [ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
Error: 'kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors='dave'' returned 2 instead of one of [0]
Error: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[control-01]/Exec[kubeadm init]/returns: change from 'notrun' to ['0'] failed: 'kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors='dave'' returned 2 instead of one of [0]
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Dependency Exec[kubeadm init] has failures: true
Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Skipping because of failed dependencies
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install Kubernetes dashboard]: Dependency Exec[kubeadm init] has failures: true
Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[Install Kubernetes dashboard]: Skipping because of failed dependencies
Notice: Applied catalog in 5.47 seconds

>

**Comment by tahoward** [comment] 2018-10-12 04:28
Ok so this is odd... I restarted etcd on each node then ran `kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors=''` and the error didn't crop up. Is there perhaps a sequencing issue? The only operation I performed was restart of etcd on each host.

**Comment by vrmerlin** [comment] 2019-02-20 16:20
i finally seemed to have fixed this problem -- the solution was to update my /etc/hostname file, to be the fully qualified host name.

**Comment by davejrt** [comment] 2019-02-20 21:00
Thanks for getting back to us with the solution

**Closed by davejrt** 2019-02-20 21:01 UTC
Labels: help wanted
