### ISSUE TITLE
It is not possible to set apiServerExtraArgs with v1alpha3 or v1beta1 config templates without setting a cloud_provider

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#276] opened 2019-04-30 21:24 UTC
## What you expected to happen?

I expected to be able to set apiserver_extra_arguments and have the values rendered into apiServerExtraArgs in the kubeadm config file.

## What happened?
This still works for v1alpha1 and used to work with v1alpha3 until it was broken by this change:

commit f46e7108acad734a77a9e6234b8d1cbdeff31019
Author: Jo Rhett <jrhett@netconsonance.com>
Date:   Tue Dec 18 15:06:21 2018 -0800

    Fix multiple errors in cloud configuration (#219)

The defect was carried into the v1beta1 config support too.

## How to reproduce it?
Set some values in apiserver_extra_arguments but do NOT set cloud_provider.
apiserver_extra_arguments will not get rendered into the kubeadm config file.

## Anything else we need to know?

This is because f46e7108acad734a77a9e6234b8d1cbdeff31019 introduced this logic in manifests/config/kubeadm.pp:
```
 92   # Need to merge the cloud configuration parameters into extra_arguments
 93   if $cloud_provider {
 94     $cloud_args = $cloud_config ? {
 95       undef   => ["cloud-provider: ${cloud_provider}"],
 96       default => ["cloud-provider: ${cloud_provider}", "cloud-config: ${cloud_config}"],
 97     }
 98     $apiserver_merged_extra_arguments = concat($apiserver_extra_arguments, $cloud_args)
 99     $controllermanager_merged_extra_arguments = $cloud_args
```
and the v1alpha3 (and later by inheritance the v1beta1) template was modified to use apiserver_merged_extra_arguments instead of apiserver_extra_arguments. If cloud_provider is not set, the manifest code

$apiserver_merged_extra_arguments = concat($apiserver_extra_arguments, $cloud_args)

is not executed.

Relevant blocks of templates:

templates/v1alpha3/config_kubeadm.yaml.erb
```
 55 <%- if @apiserver_merged_extra_arguments -%>
 56 apiServerExtraArgs:
 57   <%- @apiserver_merged_extra_arguments.each do |arg| -%>
 58   <%= arg %>
 59   <%- end -%>
 60 <%- end -%>
```
templates/v1beta1/config_kubeadm.yaml.erb
```
 57 <%- if @apiserver_merged_extra_arguments -%>
 58 apiServerExtraArgs:
 59   <%- @apiserver_merged_extra_arguments.each do |arg| -%>
 60   <%= arg %>
 61   <%- end -%>
 62 <%- end -%>
```
## Versions:
```
kubernetes puppet module 4.0.0

$ puppet --version

4.7.0

$ kubectl version

1.14.1

**Comment by nickperry** [comment] 2019-04-30 21:35
apiserver_extra_arguments is missing from the spec tests:

https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/spec/classes/config/kubeadm_spec.rb

**Comment by fydai** [comment] 2019-05-02 07:46
I think the issue here is caused by this PR (https://github.com/puppetlabs/puppetlabs-kubernetes/pull/264). If `$cloud_provider` is not set, then before the PR `$apiserver_merged_extra_arguments = $apiserver_extra_arguments` would be executed, and the yaml would be templated with the provided arguments. I will prepare a PR to fix this soon.

**Comment by sheenaajay** [comment] 2019-05-03 09:15
@nickperry Thanks for detailed information.Able to reproduce the problem
@fydai Thanks for all your help.Happy to help with reviews and verification.

**Comment by sheenaajay** [comment] 2019-05-08 08:10
Hi @fydai, Thanks for the help. Just want to check if you need help on getting the PR for the fix. We have a release planned for Kubernetes. It will good to include the fix for this issue too.

**Closed** 2019-05-10 12:12 UTC
Labels: bugfix
