### ISSUE TITLE
Token need to be manually recreated for new nodes

### ISSUE THREAD

**Issue by sunnz** [puppetlabs/puppetlabs-kubernetes#277] opened 2019-05-02 04:16 UTC
I got a controller up and working, but unless I also create nodes (workers) shortly after, I can't join them to the controller unless I manually create a new token with ``kubeadm token create``, and update ``kubernetes::token`` with the new token in hiera, since the token is only valid for 24 hours.

This means I had to manually recreate a new token everytime I need to create a new controller / worker node if it has been 24 hours since the last token has been created.

Is there a Puppet automated way to do this instead of manually? So that I can assign say a role::worker Puppet class to a node and have it configured as a worker? I am looking to dynamically create workers.

The token is only valid for 24 hours, does it even make sense to store it in hiera?

**Comment by SimonHoenscheid** [comment] 2019-06-05 09:59
Its a question of data source, hiera is the data source for puppet. We can set the ttl in the erb to 0 by default which disables expiration of the token. See docs: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/

**Comment by sheenaajay** [comment] 2019-07-24 08:05
The issue is fixed with this PR https://github.com/puppetlabs/puppetlabs-kubernetes/pull/313
Thank you.

**Closed by sheenaajay** 2019-07-24 08:05 UTC
